CREATE TABLE IF NOT EXISTS `aluno` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`nome` VARCHAR(45) NOT NULL,
	`rg` VARCHAR(45) NOT NULL,
	`login` VARCHAR(45) NOT NULL,
	`senha` VARCHAR(45) NOT NULL,
	`matricula` VARCHAR(45) NOT NULL,
	`turma` VARCHAR(45) NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `professor` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`nome` VARCHAR(45) NOT NULL,
	`rg` VARCHAR(45) NOT NULL,
	`login` VARCHAR(45) NOT NULL,
	`senha` VARCHAR(45) NOT NULL,
	`siape` VARCHAR(45) NOT NULL,
	`dtAdmissao` VARCHAR(45) NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `usuario` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`nome` VARCHAR(45) NOT NULL,
	`rg` VARCHAR(45) NOT NULL,
	`login` VARCHAR(45) NOT NULL,
	`senha` VARCHAR(45) NOT NULL,
	`turma` VARCHAR(45) NOT NULL,
	PRIMARY KEY (`id`)
);